---
extends:
- eslint:recommended
- plugin:import/errors
- plugin:import/warnings
- plugin:promise/recommended

parserOptions:
  ecmaVersion: 2021
  sourceType: module

env:
  browser: true
  es6: true
  node: true

plugins:
- import
- promise

rules:
  func-names: 0
  import/no-extraneous-dependencies: 0
  import/no-named-as-default: 0
  import/no-unresolved:
  - error
  - {}

  indent:
  - error
  - 2
  - SwitchCase: 1
    ignoredNodes:
    - ConditionalExpression
    - TemplateLiteral

  linebreak-style:
  - error
  - unix

  max-len:
  - 1
  - code: 80
    comments: 80
    ignoreUrls: true

  max-statements:
  - warn
  - 40

  no-console: 1
  no-loop-func: 2
  no-sequences: 2
  no-trailing-spaces: 0
  no-use-before-define:
  - 'off'
  - functions: false
    classes: false

  quotes:
  - error
  - single
  - allowTemplateLiterals: true
    avoidEscape: true

  semi: 0
  space-in-parens:
  - 1
  - always
  - exceptions:
    - "{}"
    - "()"
    - "[]"
    - empty

settings:
  import/ignore:
  - node_modules
